export { default as DashboardIcon } from './dashboard-icon.js';
export { default as FinancialsIcon } from './financials-icon.js';
export { default as LrnzIcon } from './lrnz-icon.js';
export { default as MenuIcon } from './menu-icon.js';
export { default as ArrowIcon } from './arrow-icon.js';
export { default as SearchIcon } from './search-icon.js';
export { default as TrashIcon } from './trash-icon.js';
export { default as ExitIcon } from './exit-icon.js';
export { default as DownloadIcon } from './download-icon.js';
