export const SIDEBAR_TOGGLED = 'SIDEBAR_TOGGLED';

// user input
//export const UPDATE_STOCK_TICKER_INPUT = 'UPDATE_STOCK_TICKER_INPUT';

// available stock tickers
export const QUERY_STOCK_TICKERS = 'QUERY_STOCK_TICKERS';
export const QUERY_STOCK_TICKERS_SUCCESS = 'QUERY_STOCK_TICKERS_SUCCESS';
export const QUERY_STOCK_TICKERS_FAILED = 'QUERY_STOCK_TICKERS_FAILED';

// retrieve stock data for single stock ticker
//export const QUERY_STOCK_DATA = 'QUERY_STOCK_DATA';
//export const QUERY_STOCK_DATA_SUCCESS = 'QUERY_STOCK_DATASUCCESSD';
//export const QUERY_STOCK_DATA_FAILED = 'QUERY_STOCK_DATA_FAILED';
