// api request actions
export const INITIATED_FETCH_REQUEST  = "INITIATED_FETCH_REQUEST";
export const SUCCESSFUL_FETCH_REQUEST = "SUCCESSFUL_FETCH_REQUEST";
export const FAILED_FETCH_REQUEST     = "FAILED_FETCH_SUCCESS";

// user interactions
export const ENTERED_DUPLICATE_STOCK     = "ENTERED_DUPLICATE_STOCK";
export const RESET_DUPLICATE_STOCK_ENTRY = "RESET_DUPLICATE_STOCK_ENTRY";
